'use strict';
const bcrypt=require('bcryptjs');
const db=require('../db');
const { asyncRoute }=require('../helpers');
const { auth }=require('./shared');
const { MODULES,ROLE_PERMISSIONS,normalizeRole,audit }=require('../access');

const LABELS={dashboard:'Dashboard',appointments:'Appointments',customers:'Customers',billing:'Billing & sales',services:'Services',team:'Team',attendance:'Attendance',inventory:'Inventory',packages:'Packages',expenses:'Expenses',reports:'Reports',loyalty:'Loyalty',greetings:'Greetings',settings:'Settings',users:'Users & access'};
const ROLES=['owner','admin','manager','receptionist','team','custom'];
const selectedPermissions=body=>{const raw=Array.isArray(body.permissions)?body.permissions:body.permissions?[body.permissions]:[];const valid=new Set(MODULES.flatMap(module=>[`${module}.view`,`${module}.manage`]));return raw.filter(permission=>valid.has(permission));};
function roleAllowed(actor,role){return actor.role==='owner'||!['owner','admin'].includes(role);}
async function ownerCount(salonId){return Number((await db.one("SELECT COUNT(*) count FROM users WHERE salon_id=:salonId AND role='owner' AND status='Active'",{salonId})).count);}
async function internalUsernameFromEmail(salonId,email){
  const local=String(email||'').split('@')[0].toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-|-$/g,'').slice(0,32)||'user';
  let username=local,suffix=1;
  while(await db.one('SELECT id FROM users WHERE salon_id=:salonId AND LOWER(username)=:username',{salonId,username})) username=`${local}-${++suffix}`.slice(0,40);
  return username;
}

module.exports=app=>{
  app.get('/users',auth,asyncRoute(async(req,res)=>{const salonId=req.user.salon_id,[rows,logs]=await Promise.all([db.rows('SELECT u.id,u.name,u.username,u.email,u.role,u.status,u.force_password_change,u.last_login,u.last_activity,u.staff_id,s.name staff_name FROM users u LEFT JOIN staff s ON s.id=u.staff_id AND s.salon_id=u.salon_id WHERE u.salon_id=:salonId ORDER BY u.id',{salonId}),db.rows('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id AND u.salon_id=a.salon_id WHERE a.salon_id=:salonId ORDER BY a.id DESC LIMIT 25',{salonId})]);res.render('users.html',{rows,logs});}));
  const form=async(req,res)=>{const salonId=req.user.salon_id,id=req.params.id?Number(req.params.id):null,row=id?await db.one('SELECT * FROM users WHERE id=:id AND salon_id=:salonId',{id,salonId}):null;if(id&&!row)return res.status(404).send('User not found');if(row&&!roleAllowed(req.user,normalizeRole(row.role)))return res.status(403).render('access_denied.html');const staff=await db.rows("SELECT id,name,role FROM staff WHERE salon_id=:salonId AND archived=0 AND status='Active' ORDER BY name",{salonId});let selected=[];try{selected=Array.isArray(row?.permissions)?row.permissions:JSON.parse(row?.permissions||'[]')}catch{}const roles=req.user.role==='owner'?ROLES:ROLES.filter(role=>!['owner','admin'].includes(role));res.render('user_form.html',{row,staff,roles,modules:MODULES,labels:LABELS,role_permissions:ROLE_PERMISSIONS,selected_permissions:selected});};
  app.get('/users/new',auth,asyncRoute(form));app.get('/users/:id/edit',auth,asyncRoute(form));
  app.post('/users/new',auth,asyncRoute(async(req,res)=>{const salonId=req.user.salon_id,role=normalizeRole(req.body.role),name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!roleAllowed(req.user,role)){req.flash('error','Only the owner can create owner or admin accounts.');return res.redirect('/users/new');}if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<8){req.flash('error','Enter a name, valid email and a password of at least 8 characters.');return res.redirect('/users/new');}if(await db.one('SELECT id FROM users WHERE LOWER(email)=:email',{email})){req.flash('error','That email is already used by another Aura account.');return res.redirect('/users/new');}const username=await internalUsernameFromEmail(salonId,email),hash=await bcrypt.hash(password,12),permissions=role==='custom'?JSON.stringify(selectedPermissions(req.body)):null,result=await db.rows('INSERT INTO users(salon_id,name,username,email,password_hash,role,status,staff_id,permissions,force_password_change,created_by) VALUES(:salonId,:name,:username,:email,:hash,:role,:status,:staffId,:permissions,:force,:createdBy)',{salonId,name,username,email,hash,role,status:req.body.status==='Inactive'?'Inactive':'Active',staffId:req.body.staff_id||null,permissions,force:req.body.force_password_change?1:0,createdBy:req.user.id});await audit(req.user.id,'user.created','user',result.insertId,`Created ${email} as ${role}`,req);req.flash('success','User created successfully. They can sign in with their email address.');res.redirect('/users');}));
  app.post('/users/:id/edit',auth,asyncRoute(async(req,res)=>{const salonId=req.user.salon_id,id=Number(req.params.id),target=await db.one('SELECT * FROM users WHERE id=:id AND salon_id=:salonId',{id,salonId});if(!target)return res.status(404).send('User not found');const role=normalizeRole(req.body.role),status=req.body.status==='Inactive'?'Inactive':'Active';if(!roleAllowed(req.user,normalizeRole(target.role))||!roleAllowed(req.user,role)){req.flash('error','Only the owner can manage owner or admin accounts.');return res.redirect('/users');}if(id===req.user.id&&(status!=='Active'||role!==req.user.role)){req.flash('error','You cannot deactivate or change your own access level.');return res.redirect(`/users/${id}/edit`);}if(target.role==='owner'&&(role!=='owner'||status!=='Active')&&await ownerCount(salonId)<=1){req.flash('error','At least one active owner account is required.');return res.redirect(`/users/${id}/edit`);}const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),permissions=role==='custom'?JSON.stringify(selectedPermissions(req.body)):null;if(!name||!/^\S+@\S+\.\S+$/.test(email)){req.flash('error','Name and a valid email are required.');return res.redirect(`/users/${id}/edit`);}if(await db.one('SELECT id FROM users WHERE LOWER(email)=:email AND id<>:id',{email,id})){req.flash('error','That email is already used by another Aura account.');return res.redirect(`/users/${id}/edit`);}await db.rows('UPDATE users SET name=:name,email=:email,role=:role,status=:status,staff_id=:staffId,permissions=:permissions WHERE id=:id AND salon_id=:salonId',{name,email,role,status,staffId:req.body.staff_id||null,permissions,id,salonId});await audit(req.user.id,'user.updated','user',id,`Updated ${target.username} to ${role}/${status}`,req);req.flash('success','User access updated.');res.redirect('/users');}));
  app.post('/users/:id/reset-password',auth,asyncRoute(async(req,res)=>{const salonId=req.user.salon_id,id=Number(req.params.id),target=await db.one('SELECT * FROM users WHERE id=:id AND salon_id=:salonId',{id,salonId}),password=String(req.body.password||'');if(!target)return res.status(404).send('User not found');if(!roleAllowed(req.user,normalizeRole(target.role))){req.flash('error','Only the owner can reset this account.');return res.redirect('/users');}if(password.length<8){req.flash('error','Temporary password must be at least 8 characters.');return res.redirect(`/users/${id}/edit`);}const hash=await bcrypt.hash(password,12);await db.rows('UPDATE users SET password_hash=:hash,force_password_change=1 WHERE id=:id AND salon_id=:salonId',{hash,id,salonId});await audit(req.user.id,'user.password_reset','user',id,`Reset password for ${target.username}`,req);req.flash('success','Temporary password saved. The user must change it at next login.');res.redirect('/users');}));
};
