'use strict';
const bcrypt=require('bcryptjs');
const db=require('../db');
const { asyncRoute }=require('../helpers');
const { auth }=require('./shared');
const { MODULES,ROLE_PERMISSIONS,normalizeRole,audit }=require('../access');

const LABELS={dashboard:'Dashboard',appointments:'Appointments',customers:'Customers',billing:'Billing & sales',services:'Services',team:'Team',inventory:'Inventory',packages:'Packages',expenses:'Expenses',reports:'Reports',loyalty:'Loyalty',greetings:'Greetings',settings:'Settings',users:'Users & access'};
const ROLES=['owner','admin','manager','receptionist','team','custom'];
const selectedPermissions=body=>{const raw=Array.isArray(body.permissions)?body.permissions:body.permissions?[body.permissions]:[];const valid=new Set(MODULES.flatMap(module=>[`${module}.view`,`${module}.manage`]));return raw.filter(permission=>valid.has(permission));};
function roleAllowed(actor,role){return actor.role==='owner'||!['owner','admin'].includes(role);}
async function ownerCount(){return Number((await db.one("SELECT COUNT(*) count FROM users WHERE role='owner' AND status='Active'")).count);}

module.exports=app=>{
  app.get('/users',auth,asyncRoute(async(req,res)=>{const[rows,logs]=await Promise.all([db.rows('SELECT u.id,u.name,u.username,u.role,u.status,u.force_password_change,u.last_login,u.last_activity,u.staff_id,s.name staff_name FROM users u LEFT JOIN staff s ON s.id=u.staff_id ORDER BY u.id'),db.rows('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 25')]);res.render('users.html',{rows,logs});}));
  const form=async(req,res)=>{const id=req.params.id?Number(req.params.id):null,row=id?await db.one('SELECT * FROM users WHERE id=:id',{id}):null;if(id&&!row)return res.status(404).send('User not found');if(row&&!roleAllowed(req.user,normalizeRole(row.role)))return res.status(403).render('access_denied.html');const staff=await db.rows("SELECT id,name,role FROM staff WHERE archived=0 AND status='Active' ORDER BY name");let selected=[];try{selected=Array.isArray(row?.permissions)?row.permissions:JSON.parse(row?.permissions||'[]')}catch{}const roles=req.user.role==='owner'?ROLES:ROLES.filter(role=>!['owner','admin'].includes(role));res.render('user_form.html',{row,staff,roles,modules:MODULES,labels:LABELS,role_permissions:ROLE_PERMISSIONS,selected_permissions:selected});};
  app.get('/users/new',auth,asyncRoute(form));app.get('/users/:id/edit',auth,asyncRoute(form));
  app.post('/users/new',auth,asyncRoute(async(req,res)=>{const role=normalizeRole(req.body.role),name=String(req.body.name||'').trim(),username=String(req.body.username||'').trim().toLowerCase(),password=String(req.body.password||'');if(!roleAllowed(req.user,role)){req.flash('error','Only the owner can create owner or admin accounts.');return res.redirect('/users/new');}if(!name||!/^[a-z0-9._-]{3,40}$/.test(username)||password.length<8){req.flash('error','Enter a name, a valid username and a password of at least 8 characters.');return res.redirect('/users/new');}if(await db.one('SELECT id FROM users WHERE username=:username',{username})){req.flash('error','That username is already in use.');return res.redirect('/users/new');}const hash=await bcrypt.hash(password,12),permissions=role==='custom'?JSON.stringify(selectedPermissions(req.body)):null,result=await db.rows('INSERT INTO users(name,username,password_hash,role,status,staff_id,permissions,force_password_change,created_by) VALUES(:name,:username,:hash,:role,:status,:staffId,:permissions,:force,:createdBy)',{name,username,hash,role,status:req.body.status==='Inactive'?'Inactive':'Active',staffId:req.body.staff_id||null,permissions,force:req.body.force_password_change?1:0,createdBy:req.user.id});await audit(req.user.id,'user.created','user',result.insertId,`Created ${username} as ${role}`,req);req.flash('success','User created successfully.');res.redirect('/users');}));
  app.post('/users/:id/edit',auth,asyncRoute(async(req,res)=>{const id=Number(req.params.id),target=await db.one('SELECT * FROM users WHERE id=:id',{id});if(!target)return res.status(404).send('User not found');const role=normalizeRole(req.body.role),status=req.body.status==='Inactive'?'Inactive':'Active';if(!roleAllowed(req.user,normalizeRole(target.role))||!roleAllowed(req.user,role)){req.flash('error','Only the owner can manage owner or admin accounts.');return res.redirect('/users');}if(id===req.user.id&&(status!=='Active'||role!==req.user.role)){req.flash('error','You cannot deactivate or change your own access level.');return res.redirect(`/users/${id}/edit`);}if(target.role==='owner'&&(role!=='owner'||status!=='Active')&&await ownerCount()<=1){req.flash('error','At least one active owner account is required.');return res.redirect(`/users/${id}/edit`);}const name=String(req.body.name||'').trim(),permissions=role==='custom'?JSON.stringify(selectedPermissions(req.body)):null;if(!name){req.flash('error','Name is required.');return res.redirect(`/users/${id}/edit`);}await db.rows('UPDATE users SET name=:name,role=:role,status=:status,staff_id=:staffId,permissions=:permissions WHERE id=:id',{name,role,status,staffId:req.body.staff_id||null,permissions,id});await audit(req.user.id,'user.updated','user',id,`Updated ${target.username} to ${role}/${status}`,req);req.flash('success','User access updated.');res.redirect('/users');}));
  app.post('/users/:id/reset-password',auth,asyncRoute(async(req,res)=>{const id=Number(req.params.id),target=await db.one('SELECT * FROM users WHERE id=:id',{id}),password=String(req.body.password||'');if(!target)return res.status(404).send('User not found');if(!roleAllowed(req.user,normalizeRole(target.role))){req.flash('error','Only the owner can reset this account.');return res.redirect('/users');}if(password.length<8){req.flash('error','Temporary password must be at least 8 characters.');return res.redirect(`/users/${id}/edit`);}const hash=await bcrypt.hash(password,12);await db.rows('UPDATE users SET password_hash=:hash,force_password_change=1 WHERE id=:id',{hash,id});await audit(req.user.id,'user.password_reset','user',id,`Reset password for ${target.username}`,req);req.flash('success','Temporary password saved. The user must change it at next login.');res.redirect('/users');}));
};
